<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'WooCommerceCategorySlider\\ByteKit\\' => array($vendorDir . '/byteever/bytekit-plugin/src'),
    'WooCommerceCategorySlider\\' => array($baseDir . '/includes'),
);
