<?php

// autoload_static.php @generated by Composer

namespace WooCommerceCategorySlider\Composer\Autoload;

class ComposerStaticInitb3c93c911810918619ab12e72a63fc14
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WooCommerceCategorySlider\\ByteKit\\' => 34,
            'WooCommerceCategorySlider\\' => 26,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WooCommerceCategorySlider\\ByteKit\\' => 
        array (
            0 => __DIR__ . '/..' . '/byteever/bytekit-plugin/src',
        ),
        'WooCommerceCategorySlider\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'WooCommerceCategorySlider\\Admin\\Admin' => __DIR__ . '/../..' . '/includes/Admin/Admin.php',
        'WooCommerceCategorySlider\\Admin\\Notices' => __DIR__ . '/../..' . '/includes/Admin/Notices.php',
        'WooCommerceCategorySlider\\ByteKit\\Admin\\Flash' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Admin/Flash.php',
        'WooCommerceCategorySlider\\ByteKit\\Admin\\Notices' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Admin/Notices.php',
        'WooCommerceCategorySlider\\ByteKit\\Interfaces\\Pluginable' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Interfaces/Pluginable.php',
        'WooCommerceCategorySlider\\ByteKit\\Interfaces\\Scriptable' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Interfaces/Scriptable.php',
        'WooCommerceCategorySlider\\ByteKit\\Plugin' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Plugin.php',
        'WooCommerceCategorySlider\\ByteKit\\Scripts' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Scripts.php',
        'WooCommerceCategorySlider\\ByteKit\\Services' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Services.php',
        'WooCommerceCategorySlider\\ByteKit\\Traits\\HasPlugin' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Traits/HasPlugin.php',
        'WooCommerceCategorySlider\\Controllers\\SliderElements' => __DIR__ . '/../..' . '/includes/Controllers/SliderElements.php',
        'WooCommerceCategorySlider\\Plugin' => __DIR__ . '/../..' . '/includes/Plugin.php',
        'WooCommerceCategorySlider\\PostTypes' => __DIR__ . '/../..' . '/includes/PostTypes.php',
        'WooCommerceCategorySlider\\RestAPI' => __DIR__ . '/../..' . '/includes/RestAPI.php',
        'WooCommerceCategorySlider\\Shortcodes\\Shortcodes' => __DIR__ . '/../..' . '/includes/Shortcodes/Shortcodes.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb3c93c911810918619ab12e72a63fc14::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb3c93c911810918619ab12e72a63fc14::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb3c93c911810918619ab12e72a63fc14::$classMap;

        }, null, ClassLoader::class);
    }
}
