<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitb3c93c911810918619ab12e72a63fc14
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('WooCommerceCategorySlider\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \WooCommerceCategorySlider\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitb3c93c911810918619ab12e72a63fc14', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \WooCommerceCategorySlider\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitb3c93c911810918619ab12e72a63fc14', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\WooCommerceCategorySlider\Composer\Autoload\ComposerStaticInitb3c93c911810918619ab12e72a63fc14::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
