<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'WooCommerceCategorySlider\\Admin\\Admin' => $baseDir . '/includes/Admin/Admin.php',
    'WooCommerceCategorySlider\\Admin\\Notices' => $baseDir . '/includes/Admin/Notices.php',
    'WooCommerceCategorySlider\\ByteKit\\Admin\\Flash' => $vendorDir . '/byteever/bytekit-plugin/src/Admin/Flash.php',
    'WooCommerceCategorySlider\\ByteKit\\Admin\\Notices' => $vendorDir . '/byteever/bytekit-plugin/src/Admin/Notices.php',
    'WooCommerceCategorySlider\\ByteKit\\Interfaces\\Pluginable' => $vendorDir . '/byteever/bytekit-plugin/src/Interfaces/Pluginable.php',
    'WooCommerceCategorySlider\\ByteKit\\Interfaces\\Scriptable' => $vendorDir . '/byteever/bytekit-plugin/src/Interfaces/Scriptable.php',
    'WooCommerceCategorySlider\\ByteKit\\Plugin' => $vendorDir . '/byteever/bytekit-plugin/src/Plugin.php',
    'WooCommerceCategorySlider\\ByteKit\\Scripts' => $vendorDir . '/byteever/bytekit-plugin/src/Scripts.php',
    'WooCommerceCategorySlider\\ByteKit\\Services' => $vendorDir . '/byteever/bytekit-plugin/src/Services.php',
    'WooCommerceCategorySlider\\ByteKit\\Traits\\HasPlugin' => $vendorDir . '/byteever/bytekit-plugin/src/Traits/HasPlugin.php',
    'WooCommerceCategorySlider\\Controllers\\SliderElements' => $baseDir . '/includes/Controllers/SliderElements.php',
    'WooCommerceCategorySlider\\Plugin' => $baseDir . '/includes/Plugin.php',
    'WooCommerceCategorySlider\\PostTypes' => $baseDir . '/includes/PostTypes.php',
    'WooCommerceCategorySlider\\RestAPI' => $baseDir . '/includes/RestAPI.php',
    'WooCommerceCategorySlider\\Shortcodes\\Shortcodes' => $baseDir . '/includes/Shortcodes/Shortcodes.php',
);
